//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM_SOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DG
    {
        public int DGID { get; set; }
        public int KHID { get; set; }
        public int SPID { get; set; }
        public Nullable<int> SAO { get; set; }
        public string BINHLUAN { get; set; }
        public Nullable<System.DateTime> NGAYDG { get; set; }
    
        public virtual KH KH { get; set; }
        public virtual SP SP { get; set; }
    }
}
