//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM_SOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GH
    {
        public int GHID { get; set; }
        public Nullable<int> HDID { get; set; }
        public Nullable<int> NVID { get; set; }
        public Nullable<System.DateTime> NGAYGIAO { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual HD HD { get; set; }
        public virtual NV NV { get; set; }
    }
}
