//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM_SOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NV()
        {
            this.GHs = new HashSet<GH>();
            this.HDs = new HashSet<HD>();
        }
    
        public int NVID { get; set; }
        public string TENNV { get; set; }
        public string CAPBAC { get; set; }
        public decimal LUONG { get; set; }
        public string SDT { get; set; }
        public Nullable<System.DateTime> NGAYVL { get; set; }
        public string DIACHI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GH> GHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HD> HDs { get; set; }
    }
}
