//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM_SOS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SOSEntities1 : DbContext
    {
        public SOSEntities1()
            : base("name=SOSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTHD> CTHDs { get; set; }
        public virtual DbSet<DG> DGs { get; set; }
        public virtual DbSet<DMSP> DMSPs { get; set; }
        public virtual DbSet<GH> GHs { get; set; }
        public virtual DbSet<HD> HDs { get; set; }
        public virtual DbSet<KH> KHs { get; set; }
        public virtual DbSet<NCC> NCCs { get; set; }
        public virtual DbSet<NV> NVs { get; set; }
        public virtual DbSet<SP> SPs { get; set; }
        public virtual DbSet<TT> TTs { get; set; }
    
        public virtual int USP_CAPNHAT_CAPBAC_NV_TU_LUONG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_CAPNHAT_CAPBAC_NV_TU_LUONG");
        }
    
        public virtual ObjectResult<Nullable<int>> USP_TAO_HOADON(Nullable<int> kHID, Nullable<int> nVID, string pHUONGTHUC, string cTHD_LIST)
        {
            var kHIDParameter = kHID.HasValue ?
                new ObjectParameter("KHID", kHID) :
                new ObjectParameter("KHID", typeof(int));
    
            var nVIDParameter = nVID.HasValue ?
                new ObjectParameter("NVID", nVID) :
                new ObjectParameter("NVID", typeof(int));
    
            var pHUONGTHUCParameter = pHUONGTHUC != null ?
                new ObjectParameter("PHUONGTHUC", pHUONGTHUC) :
                new ObjectParameter("PHUONGTHUC", typeof(string));
    
            var cTHD_LISTParameter = cTHD_LIST != null ?
                new ObjectParameter("CTHD_LIST", cTHD_LIST) :
                new ObjectParameter("CTHD_LIST", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USP_TAO_HOADON", kHIDParameter, nVIDParameter, pHUONGTHUCParameter, cTHD_LISTParameter);
        }
    
        public virtual ObjectResult<USP_TIM_SP_Result> USP_TIM_SP(string tUKHOA)
        {
            var tUKHOAParameter = tUKHOA != null ?
                new ObjectParameter("TUKHOA", tUKHOA) :
                new ObjectParameter("TUKHOA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_TIM_SP_Result>("USP_TIM_SP", tUKHOAParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> USP_THEM_SP(string tENSP, Nullable<int> dMSPID, Nullable<int> nCCID, Nullable<decimal> gIA, Nullable<int> sOLUONG)
        {
            var tENSPParameter = tENSP != null ?
                new ObjectParameter("TENSP", tENSP) :
                new ObjectParameter("TENSP", typeof(string));
    
            var dMSPIDParameter = dMSPID.HasValue ?
                new ObjectParameter("DMSPID", dMSPID) :
                new ObjectParameter("DMSPID", typeof(int));
    
            var nCCIDParameter = nCCID.HasValue ?
                new ObjectParameter("NCCID", nCCID) :
                new ObjectParameter("NCCID", typeof(int));
    
            var gIAParameter = gIA.HasValue ?
                new ObjectParameter("GIA", gIA) :
                new ObjectParameter("GIA", typeof(decimal));
    
            var sOLUONGParameter = sOLUONG.HasValue ?
                new ObjectParameter("SOLUONG", sOLUONG) :
                new ObjectParameter("SOLUONG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USP_THEM_SP", tENSPParameter, dMSPIDParameter, nCCIDParameter, gIAParameter, sOLUONGParameter);
        }
    }
}
