//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM_SOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SP()
        {
            this.CTHDs = new HashSet<CTHD>();
            this.DGs = new HashSet<DG>();
        }
    
        public int SPID { get; set; }
        public string TENSP { get; set; }
        public Nullable<int> DMSPID { get; set; }
        public Nullable<int> NCCID { get; set; }
        public decimal GIA { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string TRANGTHAI { get; set; }
        public string HINHANH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DG> DGs { get; set; }
        public virtual DMSP DMSP { get; set; }
        public virtual NCC NCC { get; set; }
    }
}
